name: Welcome Workflow

on:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print Welcome Message
        run: echo "Welcome to the project! We're glad to have you here."
